apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airun-trace-pvc
  namespace: default
  labels:
    app: airun
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
